image: alpine/edge
packages:
  - go
  - linux-pam-dev
  - scdoc
sources:
  - https://github.com/emersion/maddy
tasks:
  - build: |
      cd maddy
      go build ./...
  - test: |
      cd maddy
      go test ./... -cover -race
  - build-man-pages: |
      cd maddy/man
      scdoc < maddy.1.scd > /dev/null
      scdoc < maddy-auth.5.scd > /dev/null
      scdoc < maddy-config.5.scd > /dev/null
      scdoc < maddy-filters.5.scd > /dev/null
      scdoc < maddy-imap.5.scd > /dev/null
      scdoc < maddy-smtp.5.scd > /dev/null
      scdoc < maddy-storage.5.scd > /dev/null
      scdoc < maddy-targets.5.scd > /dev/null
      scdoc < maddy-tls.5.scd > /dev/null
