image: archlinux
packages:
  - go
  - pam
  - scdoc
sources:
  - https://github.com/foxcpp/maddy
tasks:
  - build: |
      cd maddy
      go build ./...
  - test: |
      cd maddy
      go test ./... -cover -race
  - integration-test: |
      cd maddy/tests
      ./run.sh
  - build-man-pages: |
      cd maddy/docs/man
      scdoc < maddy.1.scd > /dev/null
      scdoc < maddy-auth.5.scd > /dev/null
      scdoc < maddy-config.5.scd > /dev/null
      scdoc < maddy-filters.5.scd > /dev/null
      scdoc < maddy-imap.5.scd > /dev/null
      scdoc < maddy-smtp.5.scd > /dev/null
      scdoc < maddy-storage.5.scd > /dev/null
      scdoc < maddy-targets.5.scd > /dev/null
      scdoc < maddy-tls.5.scd > /dev/null
