image: archlinux
packages:
  - go
  - pam
  - scdoc
sources:
  - https://github.com/foxcpp/maddy
tasks:
  - build: |
      cd maddy
      go build ./...
  - test: |
      cd maddy
      go test ./... -cover -race
  - integration-test: |
      cd maddy/tests
      ./run.sh
  - build-man-pages: |
      cd maddy/docs/man
      for f in *.scd; do; scdoc < $f > /dev/null; done
