image: alpine/edge
packages:
  - go
  - linux-pam-dev
  - scdoc
sources:
  - https://github.com/emersion/maddy
tasks:
  - build: |
      cd maddy
      go build ./...
  - test: |
      cd maddy
      go test ./... -cover
  - build-man-pages: |
      cd maddy/man
      scdoc <maddy.1.scd >/dev/null
      scdoc <maddy.conf.5.scd >/dev/null
      scdoc <maddy-auth.5.scd >/dev/null
      scdoc <maddy-checks.5.scd >/dev/null
      scdoc <maddy-storage.5.scd >/dev/null
      scdoc <maddy-targets.5.scd >/dev/null
