site_name: maddy documentation

repo_url: https://github.com/foxcpp/maddy

theme: readthedocs

markdown_extensions:
  - codehilite:
      guess_lang: false

nav:
  - README.md
  - Tutorials:
    - tutorials/setting-up.md
    - tutorials/manual-installation.md
    - tutorials/alias-to-remote.md
    - tutorials/multiple-domains.md
    - tutorials/upgrading.md
  - Integration with software:
    - third-party/dovecot.md
    - third-party/smtp-servers.md
    - third-party/rspamd.md
    - third-party/mailman3.md
  - seclevels.md
  - faq.md
  - unicode.md
  - specifications.md
  - Manual pages:
    - man/_generated_maddy.1.md
    - man/_generated_maddy-auth.5.md
    - man/_generated_maddy-config.5.md
    - man/_generated_maddy-filters.5.md
    - man/_generated_maddy-imap.5.md
    - man/_generated_maddy-smtp.5.md
    - man/_generated_maddy-storage.5.md
    - man/_generated_maddy-targets.5.md
    - man/_generated_maddy-tls.5.md
  - Internals:
    - internals/quirks.md
    - internals/sqlite.md
